### ISSUE TITLE
Memory leak in 0.7.1

### ISSUE THREAD

**Issue by jccazeaux** [mikeric/rivets#430]
Hi

I've done the upgrade from 0.6.9 to 0.7.1. Since i noticed some memory leak. The objects seem to be retained after unbind.
I made a jsfiddle with a very basic bind/unbind. In the model i put a very big String (~5MB) so we can clearly see the allocations and deallocations.

## example with 0.6.9 : http://jsfiddle.net/jccazeaux/v6x47k6k/
In the chrome profiler we can see that the objects are correctly freed:
![image](https://cloud.githubusercontent.com/assets/5689583/5314063/1d535cca-7c6f-11e4-8044-e94da8438b66.png)

## Same code with 0.7.1 : http://jsfiddle.net/jccazeaux/v6x47k6k/2/
In the chrome profile we see that the objects are retained. The memory is growing.
![071](https://cloud.githubusercontent.com/assets/5689583/5314075/3f5dadf2-7c6f-11e4-8969-3193f7119296.png)

To test it, just start the "Record heap allocation" profiling type and click alternatively on "bind" and "unbind".

**Comment by Jakehp** [comment]
Yikes..

**Comment by Duder-onomy** [comment]
if you change 
```javascript
rivets.bind($("#view"), { obj :
    {
            foo: "bar",
            memoryLeak: new Array(1000).join(new Array(1000).join("XXXXX"))
     }
});
```
to:
```javascript
rivets.bind($("#view"), {
    foo: "bar",
    memoryLeak: new Array(1000).join(new Array(1000).join("XXXXX"))
});
```
Then it appears as though the memory is cleaned?
Can someone confirm (my understanding on these issues is limited)? 

If this is true, is it still the case that Rivets has a leak? It seems like Rivets has forgotten its reference to the bound properties, but that `obj` is still keeping the reference to the property `memoryLeak`?

**Comment by mikeric** [comment]
This issue was opened after this pull request has been merged in. #421 

@jccazeaux Can you verify that this issue is in fact present on master? I was already aware of the memory leak in the current release, which has been addressed in #421.

**Comment by mikeric** [comment]
Closing this. I've released 0.7.2 which includes #421.

**Comment by jccazeaux** [comment]
I was unavailable until today. I verified the 0.7.2 and it doesn't seem to solve the problem. Here is the jsfiddle with 0.7.2 : http://jsfiddle.net/4tprm3ny/2/

**Comment by docluv** [comment]
I verified the leak in jccazeaux's JSFiddle using IE's memory profiling. You can see the memory building up from the base of 3.5MB (JSFiddle baseline) to 13+MB after the bind. The bound data is not released and only compounds as you bind and unbind.
![Rivets Memory Leak](http://images.professionalaspnet.com/rivets-memory-leak.png)

**Comment by jccazeaux** [comment]
This issue should be reopened

**Comment by mikeric** [comment]
@jccazeaux, @docluv Thanks for reproducing the leak on 0.7.2. Reopening this, will take a look next chance I get.

**Comment by Jakehp** [comment]
Thanks @mikeric

**Comment by jhnns** [comment]
:+1:

**Comment by jccazeaux** [comment]
Thanks

**Comment by AMTourky** [comment]
Still occurs at 0.8.0
my object is pretty big, and leaking tons of memory

**Comment by Jakehp** [comment]
Good catch @AMTourky

**Comment by AMTourky** [comment]
Thanks @Jakehp

**Comment by jccazeaux** [comment]
Found the solution in sightglass : https://github.com/mikeric/sightglass/issues/10

**Comment by Jakehp** [comment]
Good job @jccazeaux!

**Comment by jhnns** [comment]
:+1:

**Comment by nopnop** [comment]
Nice catch @jccazeaux,
@mikeric : any plan to fix this issue soon ? 
Thanks
